// Seed reviews, case results and attorney profiles, used until the back
// office publishes records to Firestore. Every record flagged `demo: true` is
// fictional sample content and carries a visible "Sample" label.

import type { Attorney, CaseResult, Review } from "./types";

export const SEED_ATTORNEYS: Attorney[] = [
  {
    // Real person. Facts below come from the published RT Fiduciary Services
    // management team profile (2016). Bar admissions await confirmation (D15).
    slug: "temitayo-tijani",
    name: "Temitayo M. Tijani",
    title: "Managing Attorney",
    admissions: [],
    education: ["Boston University School of Law", "Ethan Hathaway Financial Training Institute, London"],
    languages: ["English", "Yoruba"],
    memberships: ["Association of Investment Advisers and Portfolio Managers of Nigeria", "Nigerian Chartered Institute of Management (Associate Member)"],
    leads: ["family", "citizenship", "appeals-waivers", "consular-processing", "estates"],
    bio: [
      "Temitayo M. Tijani is a Nigerian-trained lawyer and a graduate of the Boston University School of Law. Earlier in their career, Temitayo worked as a trust administrator and banking associate with investment banking firms in Nigeria.",
      "That fiduciary background shapes the firm's approach: careful documentation, long-term planning and close attention to families whose lives cross borders.",
    ],
    initials: "TT",
    order: 1,
    demo: false,
  },
  {
    slug: "amara-whitfield",
    name: "Amara Whitfield",
    title: "Senior Associate",
    admissions: ["New York, 2017"],
    practiceLimitation: "Practice limited to federal immigration law.",
    education: ["J.D.", "LL.M."],
    languages: ["English", "French"],
    memberships: ["American Immigration Lawyers Association (AILA)"],
    leads: ["extraordinary-ability", "national-interest-waiver", "h-1b", "l-1", "investors-founders", "employers"],
    bio: [
      "Amara Whitfield handles petitions for researchers, founders and employers, with a focus on extraordinary ability and National Interest Waiver cases.",
      "Amara builds each petition as a structured legal argument that ties every exhibit to the standard an officer applies.",
    ],
    initials: "AW",
    demo: true,
  },
];

const BASE_CASES: CaseResult[] = [
  {
    slug: "spouse-green-card-after-overstay",
    form: "I-485",
    title: "Spouse green card after a prior visa overstay",
    track: "individuals", category: "Family green card", expertise: "family",
    clientProfile: "Spouse of a U.S. citizen who entered on a visitor visa and stayed 14 months beyond it.",
    challenge: "The overstay raised questions at intake about whether the spouse could apply from inside the United States.",
    approach: "We confirmed the lawful entry, which keeps adjustment of status available to immediate relatives, and prepared a full record of the marriage with interview preparation.",
    outcome: "Green card approved at interview.", headline: "Approved at interview",
    timeline: "11 months", year: 2025, attorney: "temitayo-tijani", featured: true, demo: true,
  },
  {
    slug: "naturalization-with-old-arrest",
    form: "N-400",
    title: "Naturalization with an old arrest record",
    track: "individuals", category: "Citizenship", expertise: "citizenship",
    clientProfile: "Permanent resident for nine years with one dismissed misdemeanor arrest from 2012.",
    challenge: "Disclosure of a dismissed charge and questions about good moral character.",
    approach: "We obtained certified court dispositions, prepared a clear disclosure and practised the interview.",
    outcome: "Naturalization approved and oath ceremony attended.", headline: "Oath taken",
    timeline: "6 months", year: 2025, attorney: "temitayo-tijani", demo: true,
  },
  {
    slug: "h4-work-permit-renewal",
    form: "I-765",
    title: "H-4 work permit renewal timed around a new job",
    track: "individuals", category: "Spouse work permit", expertise: "spousal-work-authorization",
    clientProfile: "H-4 spouse of an H-1B engineer, with a job offer waiting.",
    challenge: "The current card expired within five months and automatic extensions no longer applied to new renewal filings.",
    approach: "We filed the H-4 extension and the work permit renewal together on the earliest permitted date and agreed a start-date plan with the employer.",
    outcome: "Work permit approved before the start date.", headline: "Approved before start date",
    timeline: "4 months", year: 2026, attorney: "amara-whitfield", demo: true,
  },
  {
    slug: "rfe-affidavit-of-support",
    form: "I-485",
    title: "Request for evidence on the affidavit of support",
    track: "individuals", category: "Denied or delayed", expertise: "appeals-waivers",
    clientProfile: "Marriage-based case first filed without a lawyer.",
    challenge: "A Request for Evidence stated the sponsor's income fell below 125 percent of the federal poverty guidelines.",
    approach: "We added a qualified joint sponsor with a complete Affidavit of Support and tax transcripts, and responded 30 days before the deadline.",
    outcome: "Request satisfied and green card approved.", headline: "RFE resolved, approved",
    timeline: "3 months from RFE", year: 2026, attorney: "temitayo-tijani", demo: true,
  },
  {
    slug: "immigrant-visas-for-parents",
    form: "DS-260",
    title: "Immigrant visas for both parents abroad",
    track: "individuals", category: "Family abroad", expertise: "consular-processing",
    clientProfile: "U.S. citizen in Maryland sponsoring both parents in West Africa.",
    challenge: "Civil documents showed inconsistent spellings of the parents' names.",
    approach: "We secured affidavits and corrected records before the National Visa Center stage, then prepared both parents for the embassy interview by video.",
    outcome: "Both immigrant visas issued at the first interview.", headline: "Visas issued, first interview",
    timeline: "16 months", year: 2025, attorney: "temitayo-tijani", demo: true,
  },
  {
    slug: "niw-early-career-researcher",
    form: "I-140",
    title: "National Interest Waiver for an early-career researcher",
    track: "professionals", category: "National Interest Waiver", expertise: "national-interest-waiver",
    clientProfile: "Postdoctoral researcher in public health with no employer sponsor.",
    challenge: "A modest citation count for a self-petition.",
    approach: "We built the petition on the three-part Dhanasar test, with letters from independent experts and evidence that public agencies used the research.",
    outcome: "Approved with premium processing, without a request for evidence.", headline: "Approved in 7 weeks",
    timeline: "7 weeks", year: 2026, attorney: "amara-whitfield", featured: true, demo: true,
  },
  {
    slug: "o1a-startup-founder",
    form: "I-129",
    title: "O-1A for a startup founder",
    track: "professionals", category: "Extraordinary ability", expertise: "extraordinary-ability",
    clientProfile: "Founder of a venture-backed financial technology company, previously on student status.",
    challenge: "Evidence spread across press, funding records and judging roles.",
    approach: "We mapped the evidence to four O-1A criteria, prepared expert opinion letters and used an agent as petitioner.",
    outcome: "O-1A approved.", headline: "Approved in 18 days",
    timeline: "18 days with premium processing", year: 2025, attorney: "amara-whitfield", featured: true, demo: true,
  },
  {
    slug: "eb1a-physician-scientist",
    form: "I-140",
    title: "EB-1A for a physician-scientist",
    track: "professionals", category: "Extraordinary ability", expertise: "extraordinary-ability",
    clientProfile: "Academic physician who leads clinical trials.",
    challenge: "Showing sustained acclaim beyond the home institution.",
    approach: "We documented original contributions, peer review, editorial board service and media coverage against five criteria and the final merits standard.",
    outcome: "EB-1A approved.", headline: "Approved in 3 weeks",
    timeline: "3 weeks with premium processing", year: 2026, attorney: "amara-whitfield", demo: true,
  },
  {
    slug: "l1a-new-office",
    form: "I-129",
    title: "L-1A for a manager opening a U.S. office",
    track: "professionals", category: "Intracompany transfer", expertise: "l-1",
    clientProfile: "Operations director of a West African logistics company opening a Maryland subsidiary.",
    challenge: "New office petitions require secured premises and a credible business plan.",
    approach: "We prepared the lease, corporate structure, staffing plan and financials, and planned the EB-1C green card path at the same time.",
    outcome: "L-1A approved for the initial one-year period.", headline: "New office approved",
    timeline: "5 weeks with premium processing", year: 2025, attorney: "amara-whitfield", demo: true,
  },
];

export const SEED_REVIEWS: Review[] = [
  { id: "r1", name: "Adaeze O.", location: "Silver Spring, MD", matter: "Spouse green card", expertise: "family", rating: 5, source: "sample", date: "2025-03-14", demo: true,
    quote: "I was nervous about the interview for months. The attorney walked us through every question the officer was likely to ask, and the green card arrived eleven months after we filed. I always knew where things stood." },
  { id: "r2", name: "Daniel M.", location: "Baltimore, MD", matter: "Naturalization", expertise: "citizenship", rating: 5, source: "sample", date: "2025-05-02", demo: true,
    quote: "I put off citizenship for years because of an old travel history question. One consultation answered it. Six months later I took the oath with my children watching." },
  { id: "r3", name: "Priya S.", location: "Columbia, MD", matter: "H-4 work permit", expertise: "spousal-work-authorization", rating: 5, source: "sample", date: "2026-02-20", demo: true,
    quote: "My work permit was close to expiring and a job offer was waiting. They filed on the first possible day and explained the timing to my employer, so nobody was surprised." },
  { id: "r4", name: "Kwame A.", location: "Accra, Ghana", matter: "Visas for parents", expertise: "consular-processing", rating: 5, source: "sample", date: "2025-08-11", demo: true,
    quote: "Most of my questions came late at night in Ghana. The team scheduled calls around my hours and prepared my parents for the embassy interview. Both visas were issued at the first appointment." },
  { id: "r5", name: "Dr. Lina H.", location: "Bethesda, MD", matter: "National Interest Waiver", expertise: "national-interest-waiver", rating: 5, source: "sample", date: "2026-04-09", demo: true,
    quote: "They read my research and built the petition around its national importance, not only my citation count. Approved without a request for evidence." },
  { id: "r6", name: "Marco T.", location: "Arlington, VA", matter: "O-1A visa", expertise: "extraordinary-ability", rating: 5, source: "sample", date: "2025-11-07", demo: true,
    quote: "Founders have little time to collect evidence. They gave me a precise checklist, drafted the expert letters with me and filed with premium processing. Approval came in under three weeks." },
  { id: "r7", name: "Ngozi E.", location: "Houston, TX", matter: "RFE response", expertise: "appeals-waivers", rating: 5, source: "sample", date: "2026-01-16", demo: true,
    quote: "We received a request for evidence on the affidavit of support and panicked. They found the gap, fixed it with a joint sponsor and the case moved forward within two months." },
  { id: "r8", name: "James K.", location: "Rockville, MD", matter: "Removal of conditions", expertise: "family", rating: 4, source: "sample", date: "2026-03-03", demo: true,
    quote: "Good communication and solid preparation. The process took longer than I hoped, which was down to processing times, and the firm kept me updated the whole way." },
  { id: "r9", name: "Fatima B.", location: "Germantown, MD", matter: "Wills and trusts", expertise: "estates", rating: 5, source: "sample", date: "2026-05-22", demo: true,
    quote: "We own property in two countries. They explained how a U.S. will and trust work for our children abroad in language we understood." },
  { id: "r10", name: "HR Director, software company", location: "Nationwide", matter: "Employer sponsorship", expertise: "employers", rating: 5, source: "sample", date: "2026-07-30", demo: true,
    quote: "We moved our sponsorship work to RT for one point of contact. Filings go out on schedule, and our employees get answers directly from the attorney." },
];

// Success-story detail for the sample cases. Fictional, shown with "Sample".
const STORY: Record<string, Pick<CaseResult, "details" | "evidence" | "testimonial">> = {
  "spouse-green-card-after-overstay": {
    details: [
      { label: "Category", value: "Immediate relative of a U.S. citizen" },
      { label: "Forms", value: "I-130, I-485, I-765, I-131" },
      { label: "State", value: "Maryland" },
      { label: "Interview", value: "Yes, at the Baltimore field office" },
      { label: "Request for evidence", value: "None" },
      { label: "Filing to approval", value: "11 months" },
    ],
    evidence: ["Proof of lawful admission (I-94 record)", "Joint lease, bank and insurance records", "Affidavits from family and friends", "Photographs across the relationship"],
    testimonial: "We were worried the overstay would end everything. The attorney explained the law clearly and prepared us for every question.",
  },
  "naturalization-with-old-arrest": {
    details: [
      { label: "Category", value: "Naturalization, five-year rule" },
      { label: "Form", value: "N-400" },
      { label: "State", value: "Maryland" },
      { label: "Request for evidence", value: "None" },
      { label: "Filing to oath", value: "6 months" },
    ],
    evidence: ["Certified court disposition showing dismissal", "Tax return transcripts for five years", "Written disclosure statement", "Travel history table"],
  },
  "h4-work-permit-renewal": {
    details: [
      { label: "Category", value: "H-4 spouse work authorization" },
      { label: "Forms", value: "I-539, I-765" },
      { label: "Basis", value: "Spouse's approved I-140" },
      { label: "Filing to approval", value: "4 months" },
    ],
    evidence: ["Spouse's I-140 approval notice", "Marriage certificate", "Current I-94 records for both spouses"],
  },
  "rfe-affidavit-of-support": {
    details: [
      { label: "Category", value: "Marriage-based adjustment of status" },
      { label: "Issue", value: "Request for evidence on Form I-864" },
      { label: "Response sent", value: "30 days before the deadline" },
      { label: "RFE to approval", value: "3 months" },
    ],
    evidence: ["Joint sponsor's Form I-864", "Joint sponsor's tax transcripts and pay records", "Proof of joint sponsor's U.S. citizenship"],
  },
  "immigrant-visas-for-parents": {
    details: [
      { label: "Category", value: "Parents of a U.S. citizen (IR-5)" },
      { label: "Process", value: "National Visa Center and U.S. embassy" },
      { label: "Interview", value: "Both parents, first appointment" },
      { label: "Petition to visas issued", value: "16 months" },
    ],
    evidence: ["Corrected birth records and name affidavits", "Sponsor's Affidavit of Support", "Police certificates", "Panel physician medical examinations"],
    testimonial: "They scheduled every call around my time zone and prepared my parents in their own language.",
  },
  "niw-early-career-researcher": {
    details: [
      { label: "Field", value: "Public health" },
      { label: "Position", value: "Postdoctoral researcher" },
      { label: "Category", value: "EB-2 National Interest Waiver" },
      { label: "Premium processing", value: "Yes" },
      { label: "Request for evidence", value: "None" },
      { label: "Filing to approval", value: "7 weeks" },
      { label: "Citations", value: "142" },
      { label: "Publications", value: "11 peer-reviewed articles" },
      { label: "Peer reviews", value: "14 manuscripts" },
    ],
    evidence: ["Seven letters from independent experts", "Evidence that state health agencies applied the research", "Grant funding records", "Peer review invitations and confirmations"],
    testimonial: "They understood my research better than I expected and built the case around why it matters, not around my citation count.",
  },
  "o1a-startup-founder": {
    details: [
      { label: "Field", value: "Financial technology" },
      { label: "Position", value: "Founder and chief executive" },
      { label: "Category", value: "O-1A, agent petitioner" },
      { label: "Premium processing", value: "Yes" },
      { label: "Request for evidence", value: "None" },
      { label: "Filing to approval", value: "18 days" },
    ],
    evidence: ["Venture funding from established investors", "National press coverage", "Judging roles at startup competitions", "Expert opinion letters on the company's significance"],
  },
  "eb1a-physician-scientist": {
    details: [
      { label: "Field", value: "Clinical medicine" },
      { label: "Position", value: "Academic physician" },
      { label: "Category", value: "EB-1A" },
      { label: "Premium processing", value: "Yes" },
      { label: "Request for evidence", value: "None" },
      { label: "Filing to approval", value: "3 weeks" },
      { label: "Criteria argued", value: "5 of 10" },
    ],
    evidence: ["Original contributions shown through adopted clinical protocols", "Editorial board service", "Peer review for leading journals", "Media coverage of trial results", "Leading role at a distinguished hospital"],
  },
  "l1a-new-office": {
    details: [
      { label: "Industry", value: "Logistics" },
      { label: "Position", value: "Operations director" },
      { label: "Category", value: "L-1A, new office" },
      { label: "Premium processing", value: "Yes" },
      { label: "Filing to approval", value: "5 weeks" },
      { label: "Approval period", value: "One year" },
    ],
    evidence: ["Signed commercial lease for the Maryland office", "Corporate ownership documents", "One-year staffing and business plan", "Proof of funding transfer"],
  },
};

export const SEED_CASES: CaseResult[] = BASE_CASES.map((c) => ({ ...c, ...STORY[c.slug] }));
